name: Eleventy Build
on: [push]

env:
  MY_ENVIRONMENT: production
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: josh-philpott/actions-eleventy@master
        with:
          directory: ./client
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: client/_site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: philpott-law.com
