name: Eleventy Build
on: [push]

env:
  MY_ENVIRONMENT: production
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --input client
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: client/_site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
